### ISSUE TITLE
why lumina.ai cannot filter the article when I enter the exact title of this article?

### ISSUE THREAD

**Issue by Huilin-Li** [lumina-ai-inc/benchmark#6]
**Describe the bug**
The article is "Cell-free chemoenzymatic starch synthesis from carbon dioxide" and its link is https://www.science.org/doi/10.1126/science.abh4049. Then, I typed "Cell-free chemoenzymatic starch synthesis from carbon dioxide" into lunima.ai. But lunima.ai didn't result this article in its results.
![image](https://github.com/user-attachments/assets/89db01a6-ba82-48a1-adf5-73d94da2c991)

![image](https://github.com/user-attachments/assets/3f80126a-95d4-4c1b-b668-aa728936bd0d)

**To Reproduce**
1. Go to '....'

**Expected behavior**
**I hope lumina.ai can give this article at the top of its results.**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ishaan99k** [comment]
Thank you for the detailed report! We haven't yet indexed this work as part of our database. We're currently working on adding this to our database and will update you when it is added. If you have any other questions, feel free to reach out to me on ishaan@lumina.sh
